service: serverless-rss

provider:
  name: aws
  runtime: nodejs16.x
  timeout: 25

functions:
  check:
    handler: index.check
    description: generate RSS feed from provided Vimeo username
    events:
      - http:
          path: rss
          method: get
          cors: true
          integration: lambda
          response:
            headers:
              Content-Type: "'text/xml'"
            template: $input.path('$')